# Generated by Django 4.1.7 on 2023-04-03 21:15

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_variacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(default='', force_min_size=False, upload_to='imagem', variations={'thumbnail': {'height': 500, 'width': 500}}),
            preserve_default=False,
        ),
    ]
